language:
  - ruby
git:
  depth: 1
  quiet: true
before_install:
  - sudo apt-get update -qq
bundler_args: --verbose
sudo: required
services:
  - xvfb
before_script:
  - bundle list
  - sudo apt-get install -y wkhtmltopdf
env: WKHTMLTOPDF_BIN=/usr/bin/wkhtmltopdf
script:
  - bundle exec rake
matrix:
  include:
    - rvm: 2.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.3
      gemfile: gemfiles/5.0.gemfile
      before_install:
        # https://github.com/danmayer/coverband/issues/162
        - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
        - rvm @global do gem uninstall bundler -a -x -I || true
        - gem install bundler -v '< 2'
    - rvm: 2.4
      gemfile: gemfiles/5.1.gemfile
      before_install:
        - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
        - rvm @global do gem uninstall bundler -a -x -I || true
        - gem install bundler -v '< 2'
    - rvm: 2.5
      gemfile: gemfiles/5.2.gemfile
      before_install:
        - gem update --system
        - gem install bundler
    - rvm: 2.5
      gemfile: gemfiles/rails_edge.gemfile
      before_install:
        - gem update --system
        - gem install bundler
    - rvm: 2.6
      gemfile: gemfiles/5.2.gemfile
      before_install:
        - gem update --system
        - gem install bundler
    - rvm: 2.6
      gemfile: gemfiles/6.0.gemfile
      before_install:
        - gem update --system
        - gem install bundler
    - rvm: 2.6
      gemfile: gemfiles/rails_edge.gemfile
      before_install:
        - gem update --system
        - gem install bundler
    - rvm: ruby-head
      gemfile: gemfiles/5.2.gemfile
      before_install:
        - gem install bundler -v '~> 2'
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile
      before_install:
        - gem install bundler -v '~> 2'
  allow_failures:
    - rvm: 2.5
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/3.0.gemfile
    - rvm: ruby-head
